apiVersion: v1
kind: Namespace
metadata:
  name: nua
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nua
  namespace: nua
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nebraska-update-agent
  name: nebraska-update-agent
  namespace: nua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nebraska-update-agent
  template:
    metadata:
      labels:
        app: nebraska-update-agent
    spec:
      containers:
      - image: quay.io/kinvolk/nua
        name: nebraska-update-agent
        args:
        - --nebraska-server=https://staging.updateservice.flatcar-linux.net/v1/update/
        - --app-id=io.kinvolk.demo
        - --dev
        - --verbose
        imagePullPolicy: Always
        securityContext:
          runAsUser: 65534
      serviceAccountName: nua
